use argparse::{ArgumentParser, StoreTrue, Store};

pub struct ProgramMode {
    pub monitor_mode: bool,
    pub config_file: String,
}

pub fn parse_args(pmode: &mut ProgramMode) -> bool {
    let mut ap = ArgumentParser::new();

    ap.set_description("Monitor jobs generated by `mailconfig` tool.");
    ap.refer(&mut pmode.config_file).add_option(&["-c", "--config"], Store, "Path to the HJSON config file.");
    ap.refer(&mut pmode.monitor_mode).add_option(&["-m", "--monitor"], StoreTrue, "Enable monitor mode");
    ap.parse_args_or_exit();

    true
}
